name: parkease
description: Smart Parking App - Find, Reserve, and Pay for Parking Spots

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Dependency Injection
  get_it: ^8.0.3
  
  # HTTP & API
  dio: ^5.3.2
  http: ^1.1.0
  
  # Clean Architecture
  dartz: ^0.10.1
  equatable: ^2.0.5
  connectivity_plus: ^5.0.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  
  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^2.1.1
  
  # Sensors
  sensors_plus: ^4.0.2
  camera: ^0.10.5+5
  
  # UI & Animation
  flutter_animate: ^4.2.0+1
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  
  # Navigation
  go_router: ^16.0.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.1
  # qr_code_scanner: ^1.0.1  # Temporarily disabled due to namespace issue
  
  # Payment
  # stripe_payment: ^1.1.4  # Temporarily disabled due to namespace issue
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Notifications
  # flutter_local_notifications: ^16.1.0  # Temporarily disabled due to compilation issue
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.2
  test: ^1.24.0
  fake_async: ^1.3.1
  
  # Code Generation for Mocks
  json_annotation: ^4.8.1
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700