// Mocks generated by Mockito 5.4.5 from annotations
// in parkease/test/features/profile/domain/usecases/get_user_profile_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parkease/core/error/failures.dart' as _i5;
import 'package:parkease/features/profile/domain/entities/user_profile.dart'
    as _i6;
import 'package:parkease/features/profile/domain/repositories/profile_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>> getUserProfile(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>>.value(
            _FakeEither_0<_i5.Failure, _i6.UserProfile>(
          this,
          Invocation.method(
            #getUserProfile,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>> updateUserProfile(
    String? userId,
    Map<String, dynamic>? updateData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            userId,
            updateData,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>>.value(
            _FakeEither_0<_i5.Failure, _i6.UserProfile>(
          this,
          Invocation.method(
            #updateUserProfile,
            [
              userId,
              updateData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserProfile,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteUserProfile,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>> uploadProfileImage(
    String? userId,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfileImage,
          [
            userId,
            imagePath,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>>.value(
            _FakeEither_0<_i5.Failure, _i6.UserProfile>(
          this,
          Invocation.method(
            #uploadProfileImage,
            [
              userId,
              imagePath,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfile>>);
}
