// Mocks generated by Mockito 5.4.5 from annotations
// in parkease/test/ui/screens/map/map_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parkease/core/models/parking_model.dart' as _i4;
import 'package:parkease/core/viewmodels/map_viewmodel.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MapViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapViewModel extends _i1.Mock implements _i2.MapViewModel {
  MockMapViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<_i3.Marker> get markers => (super.noSuchMethod(
        Invocation.getter(#markers),
        returnValue: <_i3.Marker>{},
      ) as Set<_i3.Marker>);

  @override
  List<_i4.ParkingLot> get parkingLots => (super.noSuchMethod(
        Invocation.getter(#parkingLots),
        returnValue: <_i4.ParkingLot>[],
      ) as List<_i4.ParkingLot>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setMapController(_i3.GoogleMapController? controller) =>
      super.noSuchMethod(
        Invocation.method(
          #setMapController,
          [controller],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectParkingLot(_i4.ParkingLot? parkingLot) => super.noSuchMethod(
        Invocation.method(
          #selectParkingLot,
          [parkingLot],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSelectedParkingLot() => super.noSuchMethod(
        Invocation.method(
          #clearSelectedParkingLot,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> moveToUserLocation() => (super.noSuchMethod(
        Invocation.method(
          #moveToUserLocation,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> searchLocation(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchLocation,
          [query],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshMapData() => (super.noSuchMethod(
        Invocation.method(
          #refreshMapData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
